### ISSUE TITLE
Exception thrown when starting application

### ISSUE THREAD

**Issue by TytanRock** [jdahlblom/DCSFlightpanels#210]
Running the dcsfp.exe (as admin or not) for the latest release does nothing.
Starting the application from command line gives the following exception in output:
```
Unhandled exception. System.IO.FileLoadException: Could not load file or assembly 'PresentationFramework, Version=6.0.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)
File name: 'PresentationFramework, Version=6.0.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
```

But if I build it from source I can run it myself.

**Comment by jdahlblom** [comment]
I really have no idea here what is going on.

**Comment by TytanRock** [comment]
I went through the releases to see the oldest release that causes this problem, and found that release `4.6.8117.1` works while `4.6.8179.1` does not.

I'd be willing to do more tests back and forth on a per-commit level, but I don't have a way to reproduce it locally. Are there instructions on your release workflow? I may be able to reproduce locally by going through your release and can help narrow it down further.

**Comment by jdahlblom** [comment]
OK, I think maybe @Mutex666 knows more about this. I just checked the 4.6.8179.1 release and can't find anything special. Did some googling too.
[Stackoverflow](https://stackoverflow.com/questions/5933189/changed-framework-version-results-in-could-not-load-file-or-assembly-presentati)
One guy apparently had this when doing some XAML changes which is actually done in that release, quite similar to what he describes. But since it works for me so I can't test anything. 
Hmm.

**Comment by Mutex666** [comment]
Hi, not familiar with this problem but it looks like this kind of error : 
[https://github.com/dotnet/wpf/issues/6109](https://github.com/dotnet/wpf/issues/6109).
I'll try to follow the workaround and tips and compile a new version with the latest version of the framework to see if it fixes the bug for you.

**Comment by Mutex666** [comment]
Hi @TytanRock . I just made a new release trying to fix your problem. I could not reproduce the problem here, can you check if it's working better for you? 

https://github.com/DCSFlightpanels/DCSFlightpanels/releases/tag/v4.6.8266.1

Thanks :-)

**Comment by TytanRock** [comment]
Sorry, no luck with 4.6.8266.1
Same behavior and exception as in the original post.

**Comment by TytanRock** [comment]
I spent more time on this and think I've got a root cause.

First, I was able to reproduce by performing the releases myself, and tested different versions.
 - 6.0.0 Works
 - 6.0.1 Didn't build
 - 6.0.2 and on produced my above problem

Then, some more googling around eventually led me to this PR, where the relevant section is the commit documenting what's going on: https://github.com/dotnet/core/pull/7346

So I checked what libraries I had installed, and saw that my Visual Studio dev environment was on version 17.0.5 with an update for 17.3.1 available. After I updated, 4.6.8266.1 worked!

I don't know what exactly updated to make it all work, but I suspect there's a dotnet package somewhere that users can update and get this to start working. Maybe it'd be worthwhile to document this in the troubleshooting section and detail my fix? Or if you know of a package that may be related, point users to that to update the relevant package?

Thanks for the help!

**Comment by Mutex666** [comment]
Hmm,

Must be a rare coincidence of installed SDK version with visual studio, compilation of the program with a bugged 6.0.2 framework and maybe other ? In the latest build I forced the framework to 6.0.4 on DCSFP project only, I should have maybe use the 6.0.0 version but for that I must also force the framework on the projects NonVisuals & ClassLibraryCommon.

I think that the fact that you updated to the latest version of Visual studio , it also installed the .net 6.0.4, maybe that solved the issue somehow.

Since I'm not a fan of forcing framework in the projet file, I'll post during a W-E a new version on master without the line so that we go back in the 'normal' state and hopefully the future new release will work for you. If not, we always have the option to force the framework usage to 6.0.0 in the 3 projects file and hope for the best.
