### ISSUE TITLE
Feature Request - Add generic module that give access to Keybind and CommonData

### ISSUE THREAD

**Issue by Drofseh** [jdahlblom/DCSFlightpanels#284]
It would be nice to have a generic module that does Keybind but also gives access to the CommonData info from DCS.

This would allow aircraft that don't have a dedicated module, such as the OV-10 mod, to still have access to info like CommonData/ALT_MSL_FT, or CommonData/HDG_DEG to use on the Multipanel or Radiopanel.

**Comment by WarLord211** [comment]
its easier to integrade the planes in BIOS as nonclickable plane to get basic read outs.
when you read this, OV-10 Mod is  (BASIC) integraded and uploaded to the master branch of FP-BIOS. 
Use FC3 profile for it.

i may concider to make it a full Integration if there is spare time and open projects are done.

**Comment by Drofseh** [comment]
I didn't even see FC3 down there in the list, thank you for pointing it out to me!
It looks like it's basically exactly what I was asking for.

**Comment by Drofseh** [comment]
Having tried it out now, unfortunately there isn't any data in BORT or DCS FP when flying the bronco with FC3 as the selected profile. Not even from the CommonData.

**Comment by WarLord211** [comment]
i checked again an i get readouts on FC3 and Common page.
NOTE: its NOT in the release, its in master branch of BIOS

**Comment by Mutex666** [comment]
Haha should have checked this issue first and the resolution that Warlord mentionned. I searched a little and I also would propose to use the FC3 profile of DCSFP to display some common values. Should work in theory. Can't test it myself since I don't have any mods installed right now

<img width="954" alt="image" src="https://user-images.githubusercontent.com/67550369/217347533-3905bf85-8b6c-4b77-827d-8868a3cc8bf7.png">
