### ISSUE TITLE
Stream Deck lose image after changing button action

### ISSUE THREAD

**Issue by jdahlblom** [jdahlblom/DCSFlightpanels#394]
Go to Stream Deck, open layer ```UFC_Actions``` and change the DCS-BIOS action for a button from ```TOGGLE``` to ```SET_STATE```. Click OK and ```Accept Changes```. 
The image is lost and it shows ```FILE NOT FOUND```.

[dcsfp_FA18C_profile_ORIG.zip](https://github.com/DCS-Skunkworks/DCSFlightpanels/files/12912438/dcsfp_FA18C_profile_ORIG.zip)

**Comment by Mutex666** [comment]
Just checked, 
It's a kind of "feature". The image preview is set to "File Not Found" if the file indicated in the relative path is not found on the HDD (when the user changes the profile path relative to DCSFP install folder or when sharing profiles). The trick is that the image is correctly embeded in the profile and that what is important, the image is well displayed in the streamdeck window.
![image](https://github.com/DCS-Skunkworks/DCSFlightpanels/assets/67550369/9ab4bd7e-df29-4852-860f-c8a1aa53a15f)

If the file is found in the relative path, no problems on the image preview
![image](https://github.com/DCS-Skunkworks/DCSFlightpanels/assets/67550369/54111083-e621-42b5-a6d4-a0cc7393399a)

We must see the image preview on the bottom right as an help to see if all the relative paths are correct, we could remove it completely or we could hide the image preview if the file is not found to not 'scare' the user.

Right now, even if all the relative paths are busted, the streamdeck windows is OK since the images are embedded / serialized. It was the goal to make the profiles shareable or resistant to folder move.

**Comment by jdahlblom** [comment]
Doing like I described in the first post causes for me :
* ```File Not Found``` being displayed in button in DCSFP
* ```File Not Found``` being displayed in preview in DCSFP
* ```File Not Found``` being displayed on Stream Deck

When saving the profile it is about 17KB smaller than before.

**Comment by Mutex666** [comment]
Damn, I could swear that it worked when I tested first, now I can reproduce the problem. I'll check.

**Comment by jdahlblom** [comment]
Yup, works fine!
